server:
    port: 8765
spring:
    application:
        name: gateway
    cloud:
        gateway:
            discovery:
                locator:
                    lower-case-service-id: true
                    enabled: true
            routes:
              - id: scaa
                uri: lb://scaa
                predicates:
                  - Path=/scaa/**
                filters:
                  - RewritePath=/scaa/?(?<remaining>.*), /$\{remaining}
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        preferIpAddress: true
        ipAddress: 127.0.0.1
  
management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always
        gateway:
            enabled: true